name: Wdrożenie do Cloudflare Workers
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Wdrożenie Workera
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          PPLX_KEY_A: ${{ secrets.PPLX_KEY_A }}
          PPLX_KEY_B: ${{ secrets.PPLX_KEY_B }}
